		
		
	</div>
	<div id="footer" >	
		<img class="border" src="images/border-footer.png">
		<ul>
			<li><a href="#">Giới thiệu</a></li>
			<li><a href="<?php echo global_common::PAGE_TERM_KM ?>">Điều khoản sử dụng</a></li>
			<li><a href="#">Câu hỏi thường gặp</a></a></li>
			<li><a href="contact.php">Liên hệ với chúng tôi</a></a></li>			
        </ul>	
		<div class="copyright">
			Copyright© 2014 oCEO.vn
		</div>	
    </div>
    <!--/div-->
</div>
</body>
</html>
