INSERT INTO sl_retailer
	(RetailerID,ProductID,
		  `ProductStatusID`,
		  `Price`,
		  `Amount`,
		  `Remaining`,
		  `ImageLink`,
		  `ShipTypeID`,
		  `ShipingCost`,
		  `ShippingDay`,
		  `ShippingDesc`,
		  `PaymentModeID`,
		  `Promotion`,
		  `ShortDesc`,
		  `Description`,
		  `CreatedBy`,
		  `CreatedDate`,
		  `ModifiedBy`,
		  `ModifiedDate`,
		  `DeletedBy`,
		  `DeletedDate`,
		  `IsDeleted`,
		  `StatusID`,
		  `Status` )  
  
  SELECT  ( RetailerID + (SELECT MAX(RetailerID) FROM sl_retailer)) AS RetailerID,ProductID,  
  `ProductStatusID`,
  `Price`,
  `Amount`,
  `Remaining`,
  `ImageLink`,
  `ShipTypeID`,
  `ShipingCost`,
  `ShippingDay`,
  `ShippingDesc`,
  `PaymentModeID`,
  `Promotion`,
  `ShortDesc`,
  `Description`,
  `CreatedBy`,
  `CreatedDate`,
  `ModifiedBy`,
  `ModifiedDate`,
  `DeletedBy`,
  `DeletedDate`,
  `IsDeleted`,
  `StatusID`,
  `Status` FROM sl_retailer 
